### ISSUE TITLE
🐛 BUG: Unexpected token '.'

### ISSUE THREAD

**Issue by jsjoeio** [withastro/language-tools#132]
### Describe the Bug

The Astro extension keeps crashing and eventually gives up and won't restart.

## Additional Context

This is inside a code-server running in the browser (Brave) on Windows 10.

### Steps to Reproduce

1. install [code-server](https://github.com/cdr/code-server) (or deploy to a [service like Railway](https://www.youtube.com/watch?v=IWfkkaY5fXs))
2. install Astro extension
3. open Astro project
4. Error! 

## Expected
syntax highlighting and the Astro extension works.

## Actual

"Astro server crashed 3 times in the last minute" (something along those lines)

```javascript
SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/coder/.local/share/code-server/extensions/astro-build.astro-vscode-0.8.3/node_modules/@astrojs/language-server/dist/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[Info  - 3:26:41 PM] Connection to server got closed. Server will restart.
/home/coder/.local/share/code-server/extensions/astro-build.astro-vscode-0.8.3/node_modules/@astrojs/language-server/dist/check.js:46
            text: this.docManager.get(uri)?.getText() || '',
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/coder/.local/share/code-server/extensions/astro-build.astro-vscode-0.8.3/node_modules/@astrojs/language-server/dist/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[Info  - 3:26:41 PM] Connection to server got closed. Server will restart.
/home/coder/.local/share/code-server/extensions/astro-build.astro-vscode-0.8.3/node_modules/@astrojs/language-server/dist/check.js:46
            text: this.docManager.get(uri)?.getText() || '',
                                           ^

SyntaxError: Unexpected token '.'
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/coder/.local/share/code-server/extensions/astro-build.astro-vscode-0.8.3/node_modules/@astrojs/language-server/dist/index.js:4:15)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
[Error - 3:26:41 PM] Connection to server got closed. Server will not be restarted
````

**Comment by Princesseuh** [comment]
This particular issue seems to be caused by using an old version of Node (since it seems to complain about optional chaining which was added in Node 14)

We don't really support versions lower than 14, our support for Node 12 has been broken for pretty much the entire existence of this project. Astro dropped Node 12 support last December and we plan to do the same for this project in the coming weeks.
