### ISSUE TITLE
🐛 BUG: Upgrading the language server to version 2.0 triggers an error in the languageService

### ISSUE THREAD

**Issue by yaegassy** [withastro/language-tools#560]
### Describe the Bug

I am using a plugin called [coc-astro](https://github.com/yaegassy/coc-astro) for Vim/Neovim. When upgrading the language server to version "2.0", it encounters an error and fails to start correctly.

The `initializationOptions` on the client-side, including `typescript.tsdk`, have been adjusted, but an error still occurs.

**e.g.**:

```
"initializationOptions": {
  "typescript": {
    "tsdk": "/Users/yaegassy/_Dev/source/coc-astro/node_modules/typescript/lib"
  },
  "diagnosticModel": 2
}
```

**Error**:

> TypeError: Cannot read properties of undefined (reading 'languageService')

<details>
<summary>Log</summary>

```
service typescript crashed on file:///Users/yaegassy/_Dev/vim/check-coc-extension/astro-check/astro-ts-check/src/pages/index.astro.tsx TypeError: Cannot read properties of undefined (reading 'languageService')
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/volar-service-typescript/out/services/diagnostics.js:12:40
    at Object.provideDiagnostics (/Users/yaegassy/_Dev/source/coc-astro/node_modules/volar-service-typescript/out/index.js:272:24)
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/languageFeatures/validation.js:261:52
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:23:65
    at safeCall (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:133:22)
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:23:50
    at async visitEmbedded (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/definePlugin.js:12:18)
    at async visitEmbedded (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/definePlugin.js:6:14)
    at async languageFeatureWorker (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:20:9)
    at async worker (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/languageFeatures/validation.js:233:28)
service typescript crashed on file:///Users/yaegassy/_Dev/vim/check-coc-extension/astro-check/astro-ts-check/src/pages/index.astro.tsx TypeError: Cannot read properties of undefined (reading 'languageService')
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/volar-service-typescript/out/services/diagnostics.js:12:40
    at Object.provideSemanticDiagnostics (/Users/yaegassy/_Dev/source/coc-astro/node_modules/volar-service-typescript/out/index.js:277:24)
    at Object.provideSemanticDiagnostics (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@astrojs/language-server/dist/plugins/typescript/index.js:53:56)
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/languageFeatures/validation.js:261:52
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:23:65
    at safeCall (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:133:22)
    at /Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:23:50
    at async visitEmbedded (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/definePlugin.js:12:18)
    at async visitEmbedded (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/definePlugin.js:6:14)
    at async languageFeatureWorker (/Users/yaegassy/_Dev/source/coc-astro/node_modules/@volar/language-service/out/utils/featureWorkers.js:20:9)
```

</details>

### Steps to Reproduce

None

**Comment by yaegassy** [comment]
This might be related? 

- <https://github.com/withastro/language-tools/pull/556>

**Comment by yaegassy** [comment]
It appears to be a situation similar to the log of comments in the following PR.

https://github.com/withastro/language-tools/pull/556#issue-1739351515

This issue will be closed. We will recheck for updates during the next release of the language server.
