### ISSUE TITLE
🐛 BUG: Regression in `astro-vscode` 2.0.14 that occurs upon loading an Astro project

### ISSUE THREAD

**Issue by wale** [withastro/language-tools#568]
### Describe the Bug

A regression that causes a `TypeError` is found in the `patchTSX` function in `packages/language-server/src/core/utils.ts`.

Stacktrace:
```
/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:239878
      return code.replace(/\b(\S*)__AstroComponent_/, (_, m1) => isDynamic ? `_${m1}_` : m1[0].toUpperCase() + m1.slice(1));
                                                                                               ^

TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at /home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:239878:96
    at [Symbol.replace] (<anonymous>)
    at String.replace (<anonymous>)
    at patchTSX (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:239878:19)
    at getVirtualFileTSX (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:239904:42)
    at astro2tsx (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:239898:22)
    at AstroFile.onSnapshotUpdated (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:240866:47)
    at new AstroFile (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:240841:14)
    at Object.createVirtualFile (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:240796:20)
    at Object.updateSource (/home/wale/.vscode/extensions/astro-build.astro-vscode-2.0.14-linux-x64/dist/node/server.js:26038:42)

```

The regression is found as follows: 
https://github.com/withastro/language-tools/blame/89b18b0d234144b3248c693deb275fe85ecd4321/packages/language-server/src/core/utils.ts#L150-L156

### Steps to Reproduce

1. Install the latest (currently `2.0.14` as of writing)
2. `npm init astro` using template <NAME>
    - This can also be induced by opening an existing Astro project.
3. Watch as the Astro extension loads up
4. Error! Message saying that the Astro extension has failed to load five times in the past three minutes

**Comment by fabiodcorreia** [comment]
I also get this, as soon as I open any `.astro` file the server crashes 5 times and shutdown.

**Comment by Princesseuh** [comment]
Oops, not sure what happened here, this worked perfectly fine in dev 🤔 Will investigate, sorry for the inconvenience. Rerolling back to the previous version can be done using the "Install Another Version" menu

**Comment by Princesseuh** [comment]
Found the issue, it happens because of `404.astro` files, which I didn't have in my dev env, I'll be releasing a patch shortly. Sorry again for the inconvenience.

**Comment by fabiodcorreia** [comment]
> Found the issue, it happens because of `404.astro` files, which I didn't have in my dev env, I'll be releasing a patch shortly. Sorry again for the inconvenience.

Yes I have a custo 404.astro! Thanks or the quick followup

**Comment by Princesseuh** [comment]
`v2.0.15` should be out now with a fix for this!
