### ISSUE TITLE
🐛 BUG: Problems with run language server

### ISSUE THREAD

**Issue by bwitczak** [withastro/language-tools#581]
### Describe the Bug

Hello everyone,

I have a problem with running the language server in the Helix editor. Interdimietly when I run the Vue file it exit. In the Helix log file, I have an output like the below:

```
2023-06-10T11:30:03.593 helix_view::theme [WARN] Theme: malformed hexcode: statusline1
2023-06-10T11:30:03.593 helix_view::theme [WARN] Theme: malformed hexcode: statusline2
2023-06-10T11:30:03.594 helix_view::theme [WARN] Theme: malformed hexcode: statusline1
2023-06-10T11:30:20.640 helix_term::application [WARN] Ignoring a client/registerCapability request because dynamic capability registration is not enabled. Please report this upstream to the language server
2023-06-10T11:30:20.892 helix_term::application [ERROR] Language Server: Method workspace/inlayHint/refresh not found in request 3
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "/nix/store/r1b289b7m3vjhkfy7sr1w0gpm407xa1f-node-dependencies-js-packages-0.0.1/lib/node_modules/vscode-jsonrpc/lib/common/connection.js:565\n"
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "                        responsePromise.reject(new messages_1.ResponseError(error.code, error.message, error.data));\n"
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "                                               ^\n"
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "\n"
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "ResponseError: Method not found: workspace/inlayHint/refresh\n"
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "    at handleResponse (/nix/store/r1b289b7m3vjhkfy7sr1w0gpm407xa1f-node-dependencies-js-packages-0.0.1/lib/node_modules/vscode-jsonrpc/lib/common/connection.js:565:48)\n"
2023-06-10T11:30:23.811 helix_lsp::transport [ERROR] err <- "    at handleMessage (/nix/store/r1b289b7m3vjhkfy7sr1w0gpm407xa1f-node-dependencies-js-packages-0.0.1/lib/node_modules/vscode-jsonrpc/lib/common/connection.js:345:13)\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "    at processMessageQueue (/nix/store/r1b289b7m3vjhkfy7sr1w0gpm407xa1f-node-dependencies-js-packages-0.0.1/lib/node_modules/vscode-jsonrpc/lib/common/connection.js:362:17)\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "    at Immediate.<anonymous> (/nix/store/r1b289b7m3vjhkfy7sr1w0gpm407xa1f-node-dependencies-js-packages-0.0.1/lib/node_modules/vscode-jsonrpc/lib/common/connection.js:334:13)\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "    at process.processImmediate (node:internal/timers:476:21) {\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "  code: -32601,\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "  data: undefined\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "}\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "\n"
2023-06-10T11:30:23.812 helix_lsp::transport [ERROR] err <- "Node.js v18.16.0\n"
2023-06-10T11:30:23.840 helix_lsp::transport [ERROR] err: <- StreamClosed
```
Have someone had a problem like the above?

### Steps to Reproduce

I'm working on NixOS so I configure it in `.nix` file like below:

```
        {
          name = "astro";
          scope = "source.astro";
          injection-regex = "astro";
          file-types = ["astro"];
          roots = ["package.json" "astro.config.js"];
          auto-format = true;
          formatter = {
            command = "prettier";
            args = ["--config" ".prettierrc"];
          };
          language-server = {
            command = "astro-ls";
            args = ["--stdio"];
          };
          config = {
            "typescript" = {
              tsdk = "${nodeDeps}/lib/node_modules/typescript/lib";
            };
            "environment" = "node";
          };
        }
```

The output from the above snippet looks like the below (language.toml):

```
[[language]]
auto-format = true
file-types = ["astro"]
injection-regex = "astro"
name = "astro"
roots = ["package.json", "astro.config.js"]
scope = "source.astro"

[language.config]
environment = "node"

[language.config.typescript]
tsdk = "/nix/store/r1b289b7m3vjhkfy7sr1w0gpm407xa1f-node-dependencies-js-packages-0.0.1/lib/node_modules/typescript/lib"

[language.formatter]
args = ["--config", ".prettierrc"]
command = "prettier"

[language.language-server]
args = ["--stdio"]
command = "astro-ls"
```

**Comment by dsaghliani** [comment]
I've got the same problem. Have you perhaps found a workaround?

**Comment by johnsoncodehk** [comment]
It's a upstream issue, fixed by https://github.com/volarjs/volar.js/commit/eb8f8d93fef4eab4d006feb50d8952863a05fdd1
