### ISSUE TITLE
🐛 BUG: ERR_UNSUPPORTED_ESM_URL_SCHEME Prettier v3

### ISSUE THREAD

**Issue by NikolaRHristov** [withastro/language-tools#605]
### Describe the Bug

When formatting `.astro` files in VSCode this error shows in the console. Prettier v3

```ts
Error: Only URLs with a scheme in: file and data are supported by the default ESM loader. On Windows, absolute paths must be valid file:// URLs. Received protocol 'f:'
    at new NodeError (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:19091:5)
    at throwIfUnsupportedURLScheme (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20134:11)
    at defaultResolve (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20171:3)
    at resolve (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20191:12)
    at importFromFile (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20206:15)
    at importFromDirectory (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20470:10)
    at file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20487:12
    at async loadPlugin (file:///F:/Developer/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:20492:28)
    at async Promise.all (index 0)
    at async Promise.all (index 1) {
  code: 'ERR_UNSUPPORTED_ESM_URL_SCHEME'
}
```

### Steps to Reproduce

Format any `.astro` file in VSCode

**Comment by Princesseuh** [comment]
Hmm, seems like a Windows issue. What does your Prettier config look like?

**Comment by NikolaRHristov** [comment]
It worked, it worked. A clean refresh and re-install. Ty @Princesseuh
