### ISSUE TITLE
🐛 BUG: TS Server crashes completely on version 2.x

### ISSUE THREAD

**Issue by otaviomad** [withastro/language-tools#614]
### Describe the Bug

Hey! This is a bit of a curveball because I haven't been able to reproduce it outside of my org's monorepository, which is full of private stuff.

I have been able to trace my steps and also have some logs that _might_ be of use, so I'll try my best to describe it.

When developing an astro page in my monorepo, I noticed that type hinting was not working at all. Not on TSX files, not on TS files and not on astro files. This problem also extended to files outside of the astro project. Upon reloading VS Code, I noticed I was getting a "TS server crashed 5 times" message. 

After some prodding, I realised that it would only happen if I opened _any_ ts/tsx/astro/js file from my local astro page package. Hinting worked fine everywhere else until I opened something from there.

Further diagnosing led me to also find out that it would only break if I had created a content collection and had `"../.astro/types.d.ts"` as a reference in my `env.d.ts` file. 

After giving up for a while, I decided to try downgrading the Astro VS Code extension to 1.0.8, and much to my surprise, types are working again. I get the proper hinting on all files, including .astro files.

I will comment in this issue a relevant tsserver log. 

### Steps to Reproduce

[tentative, couldn't find a reliable way to reproduce]
1. Using yarn berry?
2. Within a monorepo?
3. With the latest astro language server (2.1.1)
4. Create an astro app
5. Create a Content Collection
6. Run yarn dev to let astro generate its types
7. Open any file that the typescript server can work with (ts, tsx, astro, js, mjs)
8. Breaks!

**Comment by otaviomad** [comment]
Relevant tsserver log:

```log
Err 3519  [14:15:12.017] Exception on executing command {
  "seq": 2,
  "type": "request",
  "command": "updateOpen",
  "arguments": {
    "changedFiles": [],
    "closedFiles": [],
    "openFiles": [
      {
        "file": "/Users/otavio/Documents/[redacted]/src/examples/button/pretty-button/index.tsx",
        "fileContent": "import { Button } from '[redacted]';\n\nimport { prettyButton } from './styles.css';\n\nconst PrettyButton = () => (\n  <Button UNSAFE_className={prettyButton}>Pretty button</Button>\n);\n\nexport default PrettyButton;\n",
        "projectRootPath": "[redacted]",
        "scriptKindName": "TSX"
      }
    ]
  }
}:

    Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false

    Error: Debug Failure. False expression: Script kind should match provided ScriptKind:3 and sourceFile.scriptKind: 4, !entry: false
        at getDocumentRegistryEntry (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133133:11)
        at acquireOrUpdateDocument (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133161:32)
        at Object.acquireDocumentWithKey (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:133099:12)
        at getOrCreateSourceFileByPath (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141928:31)
        at Object.getOrCreateSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141907:14)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141834:42
        at Object.getSourceFileWithCache [as getSourceFile] (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:117902:24)
        at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120295:23)
        at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120215:20)
        at processImportedModules (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120644:11)
        at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120350:7)
        at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120215:20)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120164:22
        at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120133:26)
        at processSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120162:5)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120434:7
        at forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)
        at processReferencedFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120433:5)
        at findSourceFileWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120344:9)
        at findSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120215:20)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120164:22
        at getSourceFileFromReferenceWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120133:26)
        at processSourceFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:120162:5)
        at processRootFile (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:119959:5)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118714:41
        at forEach (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2325:22)
        at createProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:118714:5)
        at synchronizeHostData (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141862:15)
        at Object.getProgram (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:141936:5)
        at _AutoImportProviderProject.updateGraphWorker (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174508:41)
        at _AutoImportProviderProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174360:32)
        at _AutoImportProviderProject.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175449:37)
        at updateProjectIfDirty (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:176066:35)
        at ConfiguredProject2.getPackageJsonAutoImportProvider (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175068:9)
        at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:174386:12)
        at ConfiguredProject2.updateGraph (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:175613:24)
        at _ProjectService.createLoadAndUpdateConfiguredProject (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:177228:13)
        at _ProjectService.assignProjectToOpenedScriptInfo (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178318:26)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178598:64
        at flatMap (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:2573:17)
        at _ProjectService.applyChangesInOpenFiles (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:178598:24)
        at updateOpen (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:179778:29)
        at /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182351:69
        at IpcIOSession.executeWithRequestId (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182343:14)
        at IpcIOSession.executeCommand (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182351:29)
        at IpcIOSession.onMessage (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:182393:51)
        at process.<anonymous> (/Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js:183973:14)
        at process.emit (node:events:513:28)
        at emit (node:internal/child_process:967:14)
        at process.processTicksAndRejections (node:internal/process/task_queues:84:21)
```

redacted a bunch of stuff because of my orgs policy, but all relevant messages should be there.

**Comment by johnsoncodehk** [comment]
Hi @otaviomad, could you upload /Applications/Visual Studio Code - Insiders.app/Contents/Resources/app/extensions/node_modules/typescript/lib/tsserver.js?

**Comment by otaviomad** [comment]
[tsserver.js.zip](https://github.com/withastro/language-tools/files/12172573/tsserver.js.zip)
Here you go. I changed the TS version on VSCode to be the editor's version instead of the local one because the local one contained the folder name of my project, but the versions are the same and the errors occur on both.
