### ISSUE TITLE
🐛 BUG: VSCode - Can't format Astro files, prettier is failing.

### ISSUE THREAD

**Issue by sannajammeh** [withastro/language-tools#621]
### Describe the Bug

I have lost formatting in Astro files and getting this response from the `Astro Language Server` in VSCode

```bash
Error: printer.embed has too many parameters. The API changed in Prettier v3. Please update your plugin. See https://prettier.io/docs/en/plugins.html#optional-embed
    at printEmbeddedLanguages (file:///Users/sannajammeh/code/Cartable/cartable/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:17963:11)
    at printAstToDoc (file:///Users/sannajammeh/code/Cartable/cartable/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18094:9)
    at async coreFormat (file:///Users/sannajammeh/code/Cartable/cartable/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18405:14)
    at async formatWithCursor (file:///Users/sannajammeh/code/Cartable/cartable/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:18603:14)
    at async Module.format2 (file:///Users/sannajammeh/code/Cartable/cartable/node_modules/.pnpm/prettier@3.0.0/node_modules/prettier/index.mjs:21789:25)
    at async Object.provideDocumentFormattingEdits (/Users/sannajammeh/.vscode/extensions/astro-build.astro-vscode-2.1.4-darwin-arm64/dist/node/server.js:645:3484)
    at async g (/Users/sannajammeh/.vscode/extensions/astro-build.astro-vscode-2.1.4-darwin-arm64/dist/node/server.js:61:811)
    at async Object.format (/Users/sannajammeh/.vscode/extensions/astro-build.astro-vscode-2.1.4-darwin-arm64/dist/node/server.js:60:6566)
    at async Immediate.<anonymous> (/Users/sannajammeh/.vscode/extensions/astro-build.astro-vscode-2.1.4-darwin-arm64/dist/node/server.js:80:23759)
```

### Steps to Reproduce

1. Init astro in a monorepo using pnpm
2. Press save on a `.astro` file
3. Watch astro extension fail in vscode output

**Comment by Princesseuh** [comment]
Are you using a Prettier config? The error is implying that you have a plugin that's not compatible with Prettier 3.

**Comment by sannajammeh** [comment]
> Are you using a Prettier config? The error is implying that you have a plugin that's not compatible with Prettier 3.

No, Im not using anything. The error is coming from the astro extension itself. Ill attempt to make a repro.

**Comment by adamklepacz** [comment]
Same here. Lost prettier formatting but a different Error:

Pretty annoying. This happened for the second time this week for me but with a differnt error.
![CleanShot 2023-08-04 at 11 41 44](https://github.com/withastro/language-tools/assets/27632432/1a116a90-66a4-404d-9de3-bcafb1cfed5f)

**Comment by adamklepacz** [comment]
Okay, so for 99% there was a regression introduced in https://github.com/withastro/language-tools/commit/8ac32d965e226de6c48679129fdfa18ccdbb017d

What I did locally was to install the latest working version of Astro Language server by `npm i @astrojs/language-server@2.1.4 -D`. Then removing all node_modules from my repo with `rm -rf node_modules`, then on the last step restarting the Vscode. 

Now formating is working once again.

cc @sannajammeh you can try this as well. It works on one my collegaues machine as well (he also lost formatting this morning)

**Comment by Princesseuh** [comment]
> Okay, so for 99% there was a regression introduced in https://github.com/withastro/language-tools/commit/8ac32d965e226de6c48679129fdfa18ccdbb017d
> 
> Temporary fix:
> 1. Remove all node_modules from your repo with `rm -rf node_modules`
> 2. Install the latest working version of Astro Language server by `npm i @astrojs/language-server@2.1.4 -D` using the package manager of your choice
> 3. Then on the last step restart the Vscode. 
> 
> Now formating is working once again.
> 
> cc @sannajammeh you can try this as well. It works on one my collegaues machine as well (he also lost formatting this morning)

The VS Code extension does not use that version of the language server, it was released with 2.1.4

**Comment by minamme** [comment]
I'm also experiencing this. I think plugin update broke things

**Comment by VoxelMC** [comment]
A fix that worked for me was to `npm update prettier-plugin-astro` @sannajammeh @minamme

The latest version (0.11) of prettier-plugin-astro set the plugin to support Prettier v3 instead of v2.

Hope that helps!

**Comment by minamme** [comment]
Not working. I tried other ways like old versions of plugin as well. BTW, I'm trying to make it work in VS code

**Comment by sannajammeh** [comment]
> A fix that worked for me was to `npm update prettier-plugin-astro` @sannajammeh @minamme
> 
> The latest version (0.11) of prettier-plugin-astro set the plugin to support Prettier v3 instead of v2.
> 
> Hope that helps!

This fixes the VSCode issue.
@Princesseuh this is indeed an Astro peer dependency issue and not a project issue. If you look at the trace this comes directly from the Astro extension and uses LSP installed in node_modules.

**Comment by Princesseuh** [comment]
All those issues should be fixed in Astro 3.0, which doesn't have a dependency on Prettier or the Prettier plugin anymore.

**Comment by minamme** [comment]
Yes fixed now
