### ISSUE TITLE
🐛 BUG: Message: Pending response rejected since connection got disposed Code: -32097

### ISSUE THREAD

**Issue by jdic** [withastro/language-tools#985]
### Describe the Bug

This appears as soon as I create the [Starlight](https://starlight.astro.build/) template.

```sh
[Error - 8:34:54 PM] Server process exited with code 1.
node:internal/modules/cjs/loader:1235
  throw err;
  ^

Error: Cannot find module '@astrojs/compiler/sync'
Require stack:
- /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:668:41377
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:672:6875
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:1132:552 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js'
  ]
}

Node.js v20.18.1
[Error - 8:34:54 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 8:34:54 PM] Connection to server got closed. Server will restart.
true
[Error - 8:34:54 PM] Astro Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1235
  throw err;
  ^

Error: Cannot find module '@astrojs/compiler/sync'
Require stack:
- /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:668:41377
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:672:6875
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:1132:552 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js'
  ]
}

Node.js v20.18.1
[Error - 8:34:54 PM] Server process exited with code 1.
[Error - 8:34:55 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 8:34:55 PM] Connection to server got closed. Server will restart.
true
[Error - 8:34:55 PM] Astro Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1235
  throw err;
  ^

Error: Cannot find module '@astrojs/compiler/sync'
Require stack:
- /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:668:41377
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:672:6875
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:1132:552 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js'
  ]
}

Node.js v20.18.1
[Error - 8:34:55 PM] Server process exited with code 1.
[Error - 8:34:55 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 8:34:55 PM] Connection to server got closed. Server will restart.
true
[Error - 8:34:55 PM] Astro Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:34:55 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1235
  throw err;
  ^

Error: Cannot find module '@astrojs/compiler/sync'
Require stack:
- /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:668:41377
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:672:6875
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:1132:552 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js'
  ]
}

Node.js v20.18.1
[Error - 8:34:56 PM] Server process exited with code 1.
[Error - 8:34:56 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Info  - 8:34:56 PM] Connection to server got closed. Server will restart.
true
[Error - 8:34:56 PM] Astro Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:34:56 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 
node:internal/modules/cjs/loader:1235
  throw err;
  ^

Error: Cannot find module '@astrojs/compiler/sync'
Require stack:
- /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1232:15)
    at Module._load (node:internal/modules/cjs/loader:1058:27)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:668:41377
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:672:6875
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:2:250
    at /home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js:1132:552 {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jdi/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/dist/node/server.js'
  ]
}

Node.js v20.18.1
[Error - 8:34:58 PM] Server process exited with code 1.
[Error - 8:34:58 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:34:58 PM] The Astro Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
[Error - 8:34:58 PM] Astro Language Server client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 8:34:58 PM] Restarting server failed
  Message: Pending response rejected since connection got disposed
  Code: -32097 

```

### Steps to Reproduce

1. `pnpm create astro --template starlight`
2. Start VSCode with Astro extension

### Link to Minimal Reproducible Example

https://github.com/withastro/starlight

**Comment by Princesseuh** [comment]
Your installation of the extension seems incomplete. Did you perhaps run a tool like npkill and removed the node_modules of the extension?

**Comment by firsttris** [comment]
I had exact the same issue. 

Arch Linux AMD-B6507800X3D 6.6.72-1-lts #1 SMP PREEMPT_DYNAMIC Fri, 17 Jan 2025 14:04:26 +0000 x86_64 GNU/Linux
VSCode 1.96.4
astro-build.astro-vscode:  2.15.4

I created a new Astro Project from template, but the issue also was with an older existing project.

Removed the extension and installed it again - Didnt help.

What did help was going to ~/.vscode/extensions/astro-build.astro-vscode-2.15.4-linux-x64/

and did a "npm install".

after this the extension was working again.

**Comment by Princesseuh** [comment]
Around 100% of the time, this is due to a corrupted installation, often due to `npkill`. Closing since there's nothing actionable here.
